### ISSUE TITLE
User Friendly Options

### ISSUE THREAD

**Issue by yusuferentunc** [BioMemPhys-FAU/domhmm#12]
- [x] verbose option to plot all intermediate results (done at #29 )
- [ ] different output options such as plots, domain results
- [x] add plot saving in pdf format (done at #56 )
- [x] adding parameter options for hmm and gmm models (done at #30 )
- [ ] fix user leaflet input logic
- [ ] create lookup tables so that user doesn't have to enter all tails and heads of lipids and sterols
- [ ] implement a helper function that user use to plot specific frames clustering result
- [ ] remove unnecessary data in the end of the conclude section
- [x] add option to use HMM models from previous runs (done at #43 )
- [ ] creating online version of domhmm so that user can use it without coding (optional)
- [ ] adding dark theme option to documentation (optional)
